# Generated by Django 5.0.7 on 2024-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.JSONField(default=list)),
                ("tasks", models.JSONField(default=list)),
            ],
        ),
    ]
