# Generated by Django 5.0.7 on 2025-02-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
